### PR TITLE
Fixes #6 - json module load error on linux

### LINKED ISSUE #6: `gem_original_require': no such file to load -- JSON
I'm getting this error. Any thoughts about it? Tried to install json, json_pure. Gone throu steps you defined and created ./asana-client file but whatever I install, this is always as-is:

``` shell
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- JSON (LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/asana-client-0.0.1/lib/asana-client.rb:10
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/asana-client-0.0.1/bin/asana:3
    from /usr/local/bin/asana:19:in `load'
    from /usr/local/bin/asana:19
```

Thanks!

### PR DESCRIPTION
**Pull request by aaronfay**
Fixed for ruby 1.9.1 on linux

### CODE REVIEW

**Comment by aaronfay** [comment]
Apologies, haven't figured out how to attach the pull request to the actual issue yet...

**Comment by tmacwill** [comment]
Thanks so much!

**Comment by cheald** [comment]
Can we get a new version of the gem published with this fix?

**Comment by tmacwill** [comment]
All set!

(tm)

**Pull request merged**
